{% set name = "vaex-ml" %}
{% set version = "0.10.0" %}
{% set sha256 = "977ef654b8ad0ff093ac44c1ee27e5d034970ff9a8fd562ee5fa82430e064def" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - vaex-core >=2.0.0,<3
    - numba
    - traitlets
    - jinja2

test:
  imports:
    - vaex.ml

about:
  home: https://www.github.com/vaexio/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Machine learning support for vaex
  description: |
    Wrappers for various machine learning libraries to make them integrate into
    vaex.

extra:
  recipe-maintainers:
    - maartenbreddels
