travis:
  secure:
    BINSTAR_TOKEN: YwiBkGyHNWQhN0JobAHIIwqRT4qsdbwaPt+SCq1tu/njNt4NDoLpJ4WPwJ4NsBjNEtJE3gwQ+EisLK/KliCM2UVQTkAOuzYvNsAuAnynjfhu/cFC39iwNVsa4UFavaiqJsrM1jBptM874fF6KKKkMjWxT9lrITFXBQzXI40LamnGqSyu+6QCCdH9Nmq8es9SOgd4cXHgBEvANCeQdhCwoNdDMc9MikFDPvtbIEtnv0a5C1xdjcm0BhfP3tzlnY8VpWxTW/hEW7RHzQfGH2rLEDMmR+1Uv7J56373VeBCXx8srQExyjCZlyW9Mshzt3fcNtV3ObBBNsIVxDwg6pBR7Hn4rQrjtCg5g2I8d37xdVTIBqPfhva5RVuCajhXWKxGXgaxrMsAN/uwkESRcU58SIfqdr7a8dFFT6jKJAcXB8hPdidRzkjLKF3Muv44d6Vl3lspRv/F1OiaHkaY65XQaNXucQ96JfUI17zlDusOVqcgQNEqUgtQijd1zWytQqxAWkwgR8Tvnl1/+Q6Zyc817GvEJ/IGoufwgGDInhcWKXwoXYzU6MO7HuEcxtRI4N+gII3XCoMgVFyEb0plQFzho2dUTQD6Vwwut0fSb4PkCzIfXGCMTXz/i8N824MEcmwnD8D4uM0B2jHAahlnKml/ETbBVNlTOSf+JxL52nGH7R0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
